In [1]:
import os

print("Current working directory:")
print(os.getcwd())

print("\nFiles and folders:")
print(os.listdir())

print("\nFiles inside datasets:")
print(os.listdir("datasets"))

Current working directory:
C:\Users\Lenovo\Desktop\linear_regression_two_datasets_starter\linear_regression_two_datasets

Files and folders:
['.gitignore', '.ipynb_checkpoints', 'datasets', 'flask_app.py', 'gradio_app.py', 'Linear_Regression.ipynb', 'README.md', 'requirements.txt', 'templates', 'train_model.py']

Files inside datasets:
['README.txt']

In [2]:
import os

print(os.listdir("datasets"))

['README.txt', 'Salary_dataset.csv.csv', 'Student_perfomance.csv.csv']

In [6]:
import os

for file in os.listdir("datasets"):
    print(repr(file))

'README.txt'
'Salary_dataset.csv.csv'
'Student_perfomance.csv.csv'

In [13]:
import os

old_name = "datasets/Student_performance.csv.csv"
new_name = "datasets/Student_performance.csv"

if os.path.exists(old_name):
    os.rename(old_name, new_name)
    print("Student filename corrected!")
elif os.path.exists(new_name):
    print("Student filename is already correct!")
else:
    print("Student file not found. Please check the datasets folder.")

print("\nCurrent files:")
print(os.listdir("datasets"))

Student filename corrected!

Current files:
['README.txt', 'Salary_dataset.csv', 'Student_performance.csv']

In [14]:
import pandas as pd

salary_df = pd.read_csv("datasets/Salary_dataset.csv")

print("Salary dataset loaded successfully!")
display(salary_df.head())

print("Column names:")
print(salary_df.columns.tolist())

Salary dataset loaded successfully!

   Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

Column names:
['Unnamed: 0', 'YearsExperience', 'Salary']

In [15]:
student_df = pd.read_csv("datasets/Student_performance.csv")

print("Student dataset loaded successfully!")
display(student_df.head())

print("Column names:")
print(student_df.columns.tolist())

Student dataset loaded successfully!

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

Column names:
['Hours_Studied', 'Attendance', 'Parental_Involvement', 'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours', 'Previous_Scores', 'Motivation_Level', 'Internet_Access', 'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type', 'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities', 'Parental_Education_Level', 'Distance_from_Home', 'Gender', 'Exam_Score']

In [16]:
print("Salary Dataset Columns:")
print(salary_df.columns.tolist())

print("\nStudent Dataset Columns:")
print(student_df.columns.tolist())

Salary Dataset Columns:
['Unnamed: 0', 'YearsExperience', 'Salary']

Student Dataset Columns:
['Hours_Studied', 'Attendance', 'Parental_Involvement', 'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours', 'Previous_Scores', 'Motivation_Level', 'Internet_Access', 'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type', 'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities', 'Parental_Education_Level', 'Distance_from_Home', 'Gender', 'Exam_Score']

In [17]:
# Prepare the Salary Dataset
salary_df = salary_df[['YearsExperience', 'Salary']].dropna()

X_salary = salary_df[['YearsExperience']]
y_salary = salary_df['Salary']


# Prepare the Student Dataset
student_df = student_df[['Hours_Studied', 'Exam_Score']].dropna()

X_student = student_df[['Hours_Studied']]
y_student = student_df['Exam_Score']


print("Both datasets are prepared successfully!")

print("Salary dataset shape:", salary_df.shape)
print("Student dataset shape:", student_df.shape)

Both datasets are prepared successfully!
Salary dataset shape: (30, 2)
Student dataset shape: (6607, 2)

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

# Salary Prediction Model
X_train_salary, X_test_salary, y_train_salary, y_test_salary = train_test_split(
    X_salary, y_salary, test_size=0.2, random_state=42
)

salary_model = LinearRegression()
salary_model.fit(X_train_salary, y_train_salary)

salary_predictions = salary_model.predict(X_test_salary)

print("SALARY PREDICTION MODEL")
print("Mean Absolute Error:", mean_absolute_error(y_test_salary, salary_predictions))
print("R2 Score:", r2_score(y_test_salary, salary_predictions))


# Student Exam Score Prediction Model
X_train_student, X_test_student, y_train_student, y_test_student = train_test_split(
    X_student, y_student, test_size=0.2, random_state=42
)

student_model = LinearRegression()
student_model.fit(X_train_student, y_train_student)

student_predictions = student_model.predict(X_test_student)

print("\nSTUDENT EXAM SCORE MODEL")
print("Mean Absolute Error:", mean_absolute_error(y_test_student, student_predictions))
print("R2 Score:", r2_score(y_test_student, student_predictions))

SALARY PREDICTION MODEL
Mean Absolute Error: 6286.453830757745
R2 Score: 0.9024461774180498

STUDENT EXAM SCORE MODEL
Mean Absolute Error: 2.4475687452945647
R2 Score: 0.2319868674542105

In [19]:
import joblib
import os

# Create a folder to store the models
os.makedirs("models", exist_ok=True)

# Save both trained models
joblib.dump(salary_model, "models/salary_model.pkl")
joblib.dump(student_model, "models/student_model.pkl")

print("Both models saved successfully!")
print("Models folder created.")

Both models saved successfully!
Models folder created.

In [20]:
%pip install gradio joblib scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting gradio
  Downloading gradio-6.30.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: joblib in c:\programdata\anaconda3\lib\site-packages (1.5.2)
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (4.10.0)
Collecting audioop-lts<=0.2.2 (from gradio)
  Downloading audioop_lts-0.2.2-cp313-abi3-win_amd64.whl.metadata (2.0 kB)
Collecting brotli>=1.1.0 (from gradio)
  Downloading brotli-1.2.0-cp313-cp313-win_amd64.whl.metadata (6.3 kB)
Collecting fastapi<1.0,>=0.115.2 (from gradio)
  Downloading fastapi-0.143.0-py3-none-any.whl.metadata (26 kB)
Collecting gradio-client==2.7.2 (from gradio)
  Downloading gradio_client-2.7.2-py3-none-any.whl.metadata (7.1 kB)
Collecting groovy~=0.1 (from gradio)
  Downloading groovy-0.1.2-py3-none-any.whl.metadata (6.1 kB)
Collecting hf-gradio<1.0,>=0.4.1 (from gradio)
  Downloading hf_gradio-0.4.1-py3-none-any.whl.metadata (428 bytes)
Requirement already satisfied: httpx<1.0,>=0.24.1 in c:\programdata\anaconda3\lib\site-packages (from gradio) (0.28.1)
Collecting huggingface-hub<3.0,>=1.16.0 (from gradio)
  Downloading huggingface_hub-2.2.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: jinja2<4.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (3.0.2)
Requirement already satisfied: numpy<3.0,>=1.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (2.3.5)
Collecting orjson~=3.0 (from gradio)
  Downloading orjson-3.13.0-cp313-cp313-win_amd64.whl.metadata (43 kB)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from gradio) (25.0)
Requirement already satisfied: pandas<4.0,>=1.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (2.3.3)
Requirement already satisfied: pillow<13.0,>=8.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (12.0.0)
Requirement already satisfied: pydantic<=3.0,>=2.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (2.12.4)
Collecting pydub<1.0 (from gradio)
  Downloading pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting python-multipart<1.0,>=0.0.18 (from gradio)
  Downloading python_multipart-0.0.32-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: pytz>=2017.2 in c:\programdata\anaconda3\lib\site-packages (from gradio) (2025.2)
Requirement already satisfied: pyyaml<7.0,>=5.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (6.0.3)
Collecting safehttpx<0.2.0,>=0.1.7 (from gradio)
  Downloading safehttpx-0.1.7-py3-none-any.whl.metadata (4.2 kB)
Collecting semantic-version~=2.0 (from gradio)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting starlette<2.0,>=1.0.1 (from gradio)
  Downloading starlette-1.7.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: tomlkit<0.15.0,>=0.12.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in c:\programdata\anaconda3\lib\site-packages (from gradio) (0.20.0)
Requirement already satisfied: typing-extensions~=4.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (4.15.0)
Collecting uvicorn>=0.14.0 (from gradio)
  Downloading uvicorn-0.54.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: fsspec in c:\programdata\anaconda3\lib\site-packages (from gradio-client==2.7.2->gradio) (2025.10.0)
Requirement already satisfied: idna>=2.8 in c:\programdata\anaconda3\lib\site-packages (from anyio<5.0,>=3.0->gradio) (3.11)
Requirement already satisfied: sniffio>=1.1 in c:\programdata\anaconda3\lib\site-packages (from anyio<5.0,>=3.0->gradio) (1.3.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\programdata\anaconda3\lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Collecting annotated-doc>=0.0.2 (from fastapi<1.0,>=0.115.2->gradio)
  Downloading annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Collecting opentelemetry-api>=1.44.0 (from fastapi<1.0,>=0.115.2->gradio)
  Downloading opentelemetry_api-1.45.1-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: certifi in c:\programdata\anaconda3\lib\site-packages (from httpx<1.0,>=0.24.1->gradio) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\programdata\anaconda3\lib\site-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\programdata\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub<3.0,>=1.16.0->gradio)
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in c:\programdata\anaconda3\lib\site-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (3.20.0)
Collecting hf-xet<2.0.0,>=1.6.0 (from huggingface-hub<3.0,>=1.16.0->gradio)
  Downloading hf_xet-1.7.0-cp38-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting httpx2<3,>=2.0.0 (from huggingface-hub<3.0,>=1.16.0->gradio)
  Downloading httpx2-2.13.1-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: tqdm>=4.42.1 in c:\programdata\anaconda3\lib\site-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (4.67.1)
Collecting httpcore2==2.13.1 (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.16.0->gradio)
  Downloading httpcore2-2.13.1-py3-none-any.whl.metadata (26 kB)
Collecting idna>=2.8 (from anyio<5.0,>=3.0->gradio)
  Downloading idna-3.20-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: truststore>=0.10 in c:\programdata\anaconda3\lib\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.16.0->gradio) (0.10.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas<4.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas<4.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\programdata\anaconda3\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\programdata\anaconda3\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (2.41.5)
Requirement already satisfied: shellingham>=1.3.0 in c:\programdata\anaconda3\lib\site-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\programdata\anaconda3\lib\site-packages (from typer<1.0,>=0.12->gradio) (14.2.0)
Requirement already satisfied: scipy>=1.8.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<4.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\programdata\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm>=4.42.1->huggingface-hub<3.0,>=1.16.0->gradio) (0.4.6)
Downloading gradio-6.30.0-py3-none-any.whl (31.4 MB)
   ---------------------------------------- 0.0/31.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/31.4 MB ? eta -:--:--
   - -------------------------------------- 0.8/31.4 MB 3.7 MB/s eta 0:00:09
   ---- ----------------------------------- 3.1/31.4 MB 6.8 MB/s eta 0:00:05
   ------- -------------------------------- 5.8/31.4 MB 8.6 MB/s eta 0:00:03
   ---------- ----------------------------- 8.4/31.4 MB 9.5 MB/s eta 0:00:03
   -------------- ------------------------- 11.0/31.4 MB 10.1 MB/s eta 0:00:03
   -------------- ------------------------- 11.3/31.4 MB 10.0 MB/s eta 0:00:03
   --------------- ------------------------ 12.3/31.4 MB 8.1 MB/s eta 0:00:03
   ---------------- ----------------------- 12.8/31.4 MB 7.3 MB/s eta 0:00:03
   ---------------- ----------------------- 13.1/31.4 MB 6.9 MB/s eta 0:00:03
   ----------------- ---------------------- 13.6/31.4 MB 6.4 MB/s eta 0:00:03
   ------------------ --------------------- 14.2/31.4 MB 6.0 MB/s eta 0:00:03
   ------------------ --------------------- 14.7/31.4 MB 5.6 MB/s eta 0:00:03
   ------------------- -------------------- 15.2/31.4 MB 5.3 MB/s eta 0:00:04
   -------------------- ------------------- 15.7/31.4 MB 5.1 MB/s eta 0:00:04
   --------------------- ------------------ 16.8/31.4 MB 5.0 MB/s eta 0:00:03
   ------------------------- -------------- 19.7/31.4 MB 5.5 MB/s eta 0:00:03
   ---------------------------- ----------- 22.5/31.4 MB 5.9 MB/s eta 0:00:02
   ------------------------------- -------- 24.4/31.4 MB 6.2 MB/s eta 0:00:02
   ------------------------------- -------- 24.4/31.4 MB 6.2 MB/s eta 0:00:02
   -------------------------------- ------- 25.4/31.4 MB 5.7 MB/s eta 0:00:02
   -------------------------------- ------- 25.7/31.4 MB 5.6 MB/s eta 0:00:02
   --------------------------------- ------ 26.2/31.4 MB 5.4 MB/s eta 0:00:01
   --------------------------------- ------ 26.5/31.4 MB 5.2 MB/s eta 0:00:01
   ---------------------------------- ----- 27.3/31.4 MB 5.1 MB/s eta 0:00:01
   -------------------------------------- - 30.1/31.4 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------  31.2/31.4 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------  31.2/31.4 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------- 31.4/31.4 MB 5.2 MB/s  0:00:06
Downloading gradio_client-2.7.2-py3-none-any.whl (64 kB)
Downloading audioop_lts-0.2.2-cp313-abi3-win_amd64.whl (30 kB)
Downloading fastapi-0.143.0-py3-none-any.whl (144 kB)
Downloading groovy-0.1.2-py3-none-any.whl (14 kB)
Downloading hf_gradio-0.4.1-py3-none-any.whl (4.5 kB)
Downloading huggingface_hub-2.2.0-py3-none-any.whl (839 kB)
   ---------------------------------------- 0.0/839.9 kB ? eta -:--:--
   ---------------------------------------- 839.9/839.9 kB 9.3 MB/s  0:00:00
Downloading click-8.5.0-py3-none-any.whl (125 kB)
Downloading hf_xet-1.7.0-cp38-abi3-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   --------------------------- ------------ 2.6/3.8 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 9.8 MB/s  0:00:00
Downloading httpx2-2.13.1-py3-none-any.whl (95 kB)
Downloading httpcore2-2.13.1-py3-none-any.whl (83 kB)
Downloading orjson-3.13.0-cp313-cp313-win_amd64.whl (121 kB)
Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Downloading python_multipart-0.0.32-py3-none-any.whl (30 kB)
Downloading safehttpx-0.1.7-py3-none-any.whl (9.0 kB)
Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Downloading starlette-1.7.0-py3-none-any.whl (78 kB)
Downloading annotated_doc-0.0.5-py3-none-any.whl (5.3 kB)
Downloading brotli-1.2.0-cp313-cp313-win_amd64.whl (369 kB)
Downloading idna-3.20-py3-none-any.whl (69 kB)
Downloading opentelemetry_api-1.45.1-py3-none-any.whl (60 kB)
Downloading uvicorn-0.54.0-py3-none-any.whl (87 kB)
Installing collected packages: pydub, brotli, semantic-version, python-multipart, orjson, opentelemetry-api, idna, httpcore2, hf-xet, groovy, click, audioop-lts, annotated-doc, uvicorn, starlette, httpx2, safehttpx, huggingface-hub, fastapi, gradio-client, hf-gradio, gradio

   ----------------------------------------  0/22 [pydub]
   ----------------------------------------  0/22 [pydub]
   ----------------------------------------  0/22 [pydub]
   - --------------------------------------  1/22 [brotli]
   --- ------------------------------------  2/22 [semantic-version]
   ----- ----------------------------------  3/22 [python-multipart]
   ----- ----------------------------------  3/22 [python-multipart]
   ----- ----------------------------------  3/22 [python-multipart]
   ------- --------------------------------  4/22 [orjson]
   --------- ------------------------------  5/22 [opentelemetry-api]
   --------- ------------------------------  5/22 [opentelemetry-api]
   --------- ------------------------------  5/22 [opentelemetry-api]
   --------- ------------------------------  5/22 [opentelemetry-api]
   --------- ------------------------------  5/22 [opentelemetry-api]
   --------- ------------------------------  5/22 [opentelemetry-api]
   --------- ------------------------------  5/22 [opentelemetry-api]
   --------- ------------------------------  5/22 [opentelemetry-api]
   ---------- -----------------------------  6/22 [idna]
   ---------- -----------------------------  6/22 [idna]
   ---------- -----------------------------  6/22 [idna]
   ---------- -----------------------------  6/22 [idna]
   ------------ ---------------------------  7/22 [httpcore2]
   ------------ ---------------------------  7/22 [httpcore2]
   ------------ ---------------------------  7/22 [httpcore2]
   ------------ ---------------------------  7/22 [httpcore2]
   ------------ ---------------------------  7/22 [httpcore2]
   ------------ ---------------------------  7/22 [httpcore2]
   ------------ ---------------------------  7/22 [httpcore2]
   ------------ ---------------------------  7/22 [httpcore2]
   ------------ ---------------------------  7/22 [httpcore2]
   -------------- -------------------------  8/22 [hf-xet]
   ---------------- -----------------------  9/22 [groovy]
   ------------------ --------------------- 10/22 [click]
   ------------------ --------------------- 10/22 [click]
   ------------------ --------------------- 10/22 [click]
   ------------------ --------------------- 10/22 [click]
   ------------------ --------------------- 10/22 [click]
   ------------------ --------------------- 10/22 [click]
   ------------------ --------------------- 10/22 [click]
   -------------------- ------------------- 11/22 [audioop-lts]
   --------------------- ------------------ 12/22 [annotated-doc]
   ----------------------- ---------------- 13/22 [uvicorn]
   ----------------------- ---------------- 13/22 [uvicorn]
   ----------------------- ---------------- 13/22 [uvicorn]
   ----------------------- ---------------- 13/22 [uvicorn]
   ----------------------- ---------------- 13/22 [uvicorn]
   ----------------------- ---------------- 13/22 [uvicorn]
   ----------------------- ---------------- 13/22 [uvicorn]
   ----------------------- ---------------- 13/22 [uvicorn]
   ----------------------- ---------------- 13/22 [uvicorn]
   ----------------------- ---------------- 13/22 [uvicorn]
   ----------------------- ---------------- 13/22 [uvicorn]
   ----------------------- ---------------- 13/22 [uvicorn]
   ------------------------- -------------- 14/22 [starlette]
   ------------------------- -------------- 14/22 [starlette]
   ------------------------- -------------- 14/22 [starlette]
   ------------------------- -------------- 14/22 [starlette]
   ------------------------- -------------- 14/22 [starlette]
   ------------------------- -------------- 14/22 [starlette]
   ------------------------- -------------- 14/22 [starlette]
   ------------------------- -------------- 14/22 [starlette]
   ------------------------- -------------- 14/22 [starlette]
   ------------------------- -------------- 14/22 [starlette]
   --------------------------- ------------ 15/22 [httpx2]
   --------------------------- ------------ 15/22 [httpx2]
   --------------------------- ------------ 15/22 [httpx2]
   --------------------------- ------------ 15/22 [httpx2]
   --------------------------- ------------ 15/22 [httpx2]
   --------------------------- ------------ 15/22 [httpx2]
   --------------------------- ------------ 15/22 [httpx2]
   --------------------------- ------------ 15/22 [httpx2]
   --------------------------- ------------ 15/22 [httpx2]
   --------------------------- ------------ 15/22 [httpx2]
   --------------------------- ------------ 15/22 [httpx2]
   --------------------------- ------------ 15/22 [httpx2]
   --------------------------- ------------ 15/22 [httpx2]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]
   ------------------------------ --------- 17/22 [huggingface-hub]

  WARNING: The script idna.exe is installed in 'C:\Users\Lenovo\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script uvicorn.exe is installed in 'C:\Users\Lenovo\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script httpx2.exe is installed in 'C:\Users\Lenovo\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts hf.exe and tiny-agents.exe are installed in 'C:\Users\Lenovo\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script fastapi.exe is installed in 'C:\Users\Lenovo\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script hf-gradio.exe is installed in 'C:\Users\Lenovo\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts gradio.exe and upload_theme.exe are installed in 'C:\Users\Lenovo\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [21]:
import gradio as gr

print("Gradio version:", gr.__version__)
print("Gradio is ready!")

ModuleNotFoundError: No module named 'gradio'

In [22]:
%pip install gradio

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: gradio in c:\users\lenovo\appdata\roaming\python\python313\site-packages (6.30.0)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (4.10.0)
Requirement already satisfied: audioop-lts<=0.2.2 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from gradio) (0.2.2)
Requirement already satisfied: brotli>=1.1.0 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from gradio) (0.143.0)
Requirement already satisfied: gradio-client==2.7.2 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from gradio) (2.7.2)
Requirement already satisfied: groovy~=0.1 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from gradio) (0.1.2)
Requirement already satisfied: hf-gradio<1.0,>=0.4.1 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from gradio) (0.4.1)
Requirement already satisfied: httpx<1.0,>=0.24.1 in c:\programdata\anaconda3\lib\site-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<3.0,>=1.16.0 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from gradio) (2.2.0)
Requirement already satisfied: jinja2<4.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (3.0.2)
Requirement already satisfied: numpy<3.0,>=1.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (2.3.5)
Requirement already satisfied: orjson~=3.0 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from gradio) (3.13.0)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from gradio) (25.0)
Requirement already satisfied: pandas<4.0,>=1.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (2.3.3)
Requirement already satisfied: pillow<13.0,>=8.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (12.0.0)
Requirement already satisfied: pydantic<=3.0,>=2.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (2.12.4)
Requirement already satisfied: pydub<1.0 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart<1.0,>=0.0.18 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from gradio) (0.0.32)
Requirement already satisfied: pytz>=2017.2 in c:\programdata\anaconda3\lib\site-packages (from gradio) (2025.2)
Requirement already satisfied: pyyaml<7.0,>=5.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (6.0.3)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.7 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<2.0,>=1.0.1 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from gradio) (1.7.0)
Requirement already satisfied: tomlkit<0.15.0,>=0.12.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in c:\programdata\anaconda3\lib\site-packages (from gradio) (0.20.0)
Requirement already satisfied: typing-extensions~=4.0 in c:\programdata\anaconda3\lib\site-packages (from gradio) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from gradio) (0.54.0)
Requirement already satisfied: fsspec in c:\programdata\anaconda3\lib\site-packages (from gradio-client==2.7.2->gradio) (2025.10.0)
Requirement already satisfied: idna>=2.8 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from anyio<5.0,>=3.0->gradio) (3.20)
Requirement already satisfied: sniffio>=1.1 in c:\programdata\anaconda3\lib\site-packages (from anyio<5.0,>=3.0->gradio) (1.3.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\programdata\anaconda3\lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.5)
Requirement already satisfied: opentelemetry-api>=1.44.0 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from fastapi<1.0,>=0.115.2->gradio) (1.45.1)
Requirement already satisfied: certifi in c:\programdata\anaconda3\lib\site-packages (from httpx<1.0,>=0.24.1->gradio) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\programdata\anaconda3\lib\site-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\programdata\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in c:\programdata\anaconda3\lib\site-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (3.20.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (1.7.0)
Requirement already satisfied: httpx2<3,>=2.0.0 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (2.13.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\programdata\anaconda3\lib\site-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (4.67.1)
Requirement already satisfied: httpcore2==2.13.1 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.16.0->gradio) (2.13.1)
Requirement already satisfied: truststore>=0.10 in c:\programdata\anaconda3\lib\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.16.0->gradio) (0.10.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas<4.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas<4.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\programdata\anaconda3\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\programdata\anaconda3\lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (2.41.5)
Requirement already satisfied: shellingham>=1.3.0 in c:\programdata\anaconda3\lib\site-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\programdata\anaconda3\lib\site-packages (from typer<1.0,>=0.12->gradio) (14.2.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<4.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\programdata\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm>=4.42.1->huggingface-hub<3.0,>=1.16.0->gradio) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import gradio as gr

print("Gradio version:", gr.__version__)
print("Gradio is ready!")

Gradio version: 6.30.0
Gradio is ready!

In [2]:
!python gradio_app.py

^C

In [3]:
import os

print("Current folder:", os.getcwd())
print("Files in this folder:", os.listdir())

Current folder: C:\Users\Lenovo\Desktop\linear_regression_two_datasets_starter\linear_regression_two_datasets
Files in this folder: ['.gitignore', '.ipynb_checkpoints', 'datasets', 'flask_app.py', 'gradio_app.py', 'Linear_Regression.ipynb', 'models', 'README.md', 'requirements.txt', 'templates', 'train_model.py']

In [4]:
!python -u gradio_app.py

^C

In [5]:
import gradio as gr

print("Gradio imported successfully!")

demo = gr.Interface(
    fn=lambda name: "Hello, " + name,
    inputs=gr.Textbox(label="Enter your name"),
    outputs=gr.Textbox(label="Greeting")
)

print("Starting test app...")
demo.launch()

Gradio imported successfully!
Starting test app...
* Running on local URL:  http://127.0.0.1:7862
* To create a public link, set `share=True` in `launch()`.

In [6]:
!python -u gradio_app.py

^C

In [7]:
import os
import joblib

print("Checking model files...")

print("Salary model exists:", os.path.exists("models/salary_model.pkl"))
print("Student model exists:", os.path.exists("models/student_model.pkl"))

print("Loading salary model...")
salary_model = joblib.load("models/salary_model.pkl")
print("Salary model loaded!")

print("Loading student model...")
student_model = joblib.load("models/student_model.pkl")
print("Student model loaded!")

Checking model files...
Salary model exists: True
Student model exists: True
Loading salary model...
Salary model loaded!
Loading student model...
Student model loaded!

In [8]:
import joblib

salary_model = joblib.load("models/salary_model.pkl")

prediction = salary_model.predict([[3]])

print("Predicted salary for 3 years of experience:", prediction[0])

Predicted salary for 3 years of experience: 52651.647448566626

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [9]:
!python -u gradio_app.py

^C

In [10]:
with open("gradio_app.py", "r") as file:
    code = file.read()

print(code)

import gradio as gr
import joblib

# Load the trained models
salary_model = joblib.load("models/salary_model.pkl")
student_model = joblib.load("models/student_model.pkl")


# Salary prediction function
def predict_salary(years_experience):
    prediction = salary_model.predict([[years_experience]])[0]
    return f"Predicted Salary: {prediction:,.2f}"


# Student exam score prediction function
def predict_exam_score(hours_studied):
    prediction = student_model.predict([[hours_studied]])[0]
    return f"Predicted Exam Score: {prediction:.2f}"


# Salary prediction interface
salary_interface = gr.Interface(
    fn=predict_salary,
    inputs=gr.Number(label="Years of Experience"),
    outputs=gr.Textbox(label="Predicted Salary"),
    title="Salary Prediction",
    description="Predict salary based on years of work experience."
)


# Student exam score interface
student_interface = gr.Interface(
    fn=predict_exam_score,
    inputs=gr.Number(label="Hours Studied"),
    outputs=gr.Textbox(label="Predicted Exam Score"),
    title="Student Exam Score Prediction",
    description="Predict exam score based on study hours."
)


# Combine both interfaces into one application
app = gr.TabbedInterface(
    [salary_interface, student_interface],
    ["Salary Prediction", "Student Exam Score"]
)


# Launch the application
if __name__ == "__main__":
    print("Models loaded. Starting Gradio...")
    app.launch(show_error=True, quiet=False)

In [11]:
import subprocess
import sys

print("Testing Python...", flush=True)

result = subprocess.run(
    [sys.executable, "-c", "print('Python process works!')"],
    capture_output=True,
    text=True,
    timeout=15
)

print("Output:", result.stdout)
print("Errors:", result.stderr)
print("Return code:", result.returncode)

Testing Python...
Output: Python process works!

Errors:
Return code: 0

In [12]:
import subprocess
import sys

print("Starting Gradio app test...", flush=True)

process = subprocess.Popen(
    [sys.executable, "-u", "gradio_app.py"],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

print("Python process started. Waiting for output...", flush=True)

try:
    output, _ = process.communicate(timeout=20)
    print(output)
except subprocess.TimeoutExpired:
    print("The app is still running after 20 seconds.")
    process.terminate()
    output, _ = process.communicate(timeout=5)
    print("Output captured:")
    print(output)

Starting Gradio app test...
Python process started. Waiting for output...
The app is still running after 20 seconds.
Output captured:
Models loaded. Starting Gradio...
* Running on local URL:  http://127.0.0.1:7865
* To create a public link, set `share=True` in `launch()`.

In [13]:
!python -u gradio_app.py

^C